version: "3.5"

# Docker Volumes
volumes:
    db_data:
        name: db_data

# Network
networks:
    proyecto:

# Docker services     
services:
    
    # Servidor NGINX
    nginx:
        image: nginx:stable-alpine
        container_name: fredy-nginx
        restart: always
        ports:
            - 8888:80
        volumes:
            - ./src/backend:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fredy-php
            - fredy-mysql
        networks:
            - proyecto
    # Servidor NGINX 2 para frontend
    nginx2:
        build: 
            context: ./src/frontend
            dockerfile: Dockerfile
        container_name: fredy-nginx2
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./src/frontend/dist/prueba_tecnica:/usr/share/nginx/html
            - ./nginx/nginx-custom.conf:/etc/nginx/conf.d/default.conf
        networks:
            - proyecto
    php:
        build:
            context: ./src/backend
            dockerfile: Dockerfile
        container_name: fredy-php
        volumes:
            - ./src/backend:/var/www/html
        ports:
            - 9000:80
        networks:
            - proyecto

    # Mysql (BD)
    mysql:
        container_name: fredy-mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'prueba_blue_medical'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'Admin!1234'
            MYSQL_ROOT_PASSWORD: 'Admin!1234'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - proyecto
