version: "3.5"

# Docker Volumes
volumes:
    db_data:
        name: db_data

# Network


# Docker services     
services:
    
    # Servidor NGINX
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./src/backend:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.config
        depends_on:
            - php
            - mysql
        networks:
            - proyecto
    php:
        build:
            context: ./src

    # Mysql (BD)
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'prueba_blue_medical'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'Admin!1234'
            MYSQL_ROOT_PASSWORD: 'Admin!1234'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - proyecto
